### ISSUE TITLE
Does it means abs(Gx)? Why should abs(Gx) at line 86?

### ISSUE THREAD

**Issue by chaingank** [Coldmooon/ColdPdollarToolbox#1]
https://github.com/Coldmooon/ColdPdollarToolbox/blob/93685c8d12a700ebf8664afe33929ea5f9b27c47/channels/private/gradientMex.cpp#L86

**Comment by chaingank** [comment]
sorry,I mistook Gy for Gx.

**Comment by cookyecat** [comment]
@ChainGank 
Sorry for the late reply. Thanks for asking this question. 
Actually, I just add comments to the Pdollar Toolbox for better understanding. I don't modify any code and algorithm except that some lines are formatted for better readability. 
I currently only added comments to files related to the ACF feature.
